### ISSUE TITLE
Dependency updates

### ISSUE THREAD

**Issue by trevor-scheer** [apollo-server-integrations/apollo-server-integration-hapi#17]
Hey @arimus, looks like there are a lot of dependency updates in the queue. We can configure renovate to automerge patch and minor updates if that's helpful, but the major versions should get a closer look from a maintainer. Let me know if you need any help here!

**Comment by arimus** [comment]
@trevor-scheer Not a worry. I've had some family stuff to take care of and have been afk / out-of-town off and on for the past month. Didn't mean to fall behind, but such is life :) Pushed a new version with almost all the upgrades, but the node-fetch upgrade was a royal pain and will have to be done later. Happy to accept a pull request if you know the magic combo of dep updates and settings.
