### ISSUE TITLE
Determine if we can get around require().default being used in commonjs

### ISSUE THREAD

**Issue by arimus** [apollo-server-integrations/apollo-server-integration-hapi#22]
From the other thread... @terrisgit

Yeah, depending on your setup you may have to do exactly what you are doing now. Just for reference, here's a thread about default exports and babel. Some build systems have monkey-patched to make it cleaner on the importing side. Not sure that I can easily do anything that won't have downstream consequences, but I'll look into it some more.

https://stackoverflow.com/questions/33704714/cant-require-default-export-value-in-babel-6-x

**Comment by terrisgit** [comment]
@arimus It's not a problem. It just needs to be documented for the few of us who are working on legacy code that can't use ESM.

**Comment by arimus** [comment]
Yeah, no worries. I'll get the docs updated either way, but there may be an
easy fix that allows the import without the .default fix and which won't
cause other issues.

Thanks for the report and the follow up!
