### ISSUE TITLE
@apollo/server graphql playground not launches

### ISSUE THREAD

**Issue by bharat-vaggu** [apollo-server-integrations/apollo-server-integration-hapi#24]
apollo server 4 graphql playground is not launches when I integrate with hapi. I have config that all routes should have jwt token. How can I skip to validate jwt for graphql playground lanuches. It was working with apollo server 3 (in this case I was not using @as-integrations/hapi). When I started using @as-integrations/hapi with apollo server 4, it is not working. Can somebody please help.

**Comment by trevor-scheer** [comment]
@bharat-vaggu can you share a reproduction or errors you're seeing? It sounds like you might be blocking the route.

**Comment by arimus** [comment]
@bharat-vaggu 

Two things. First, make sure that you have enabled the plugin for the playground in Apollo. I'm assuming that you have done this, but adding the example here anyways:

```
const apolloServer = new ApolloServer({
  typeDefs: mergedSchemas,
  resolvers,
  plugins: [
    process.env.NODE_ENV === 'production'
      ? ApolloServerPluginLandingPageDisabled() // disable plugin in production mode
      : ApolloServerPluginLandingPageGraphQLPlayground() // enable plugin in non-production mode
  ]
});
```

And then you can configure your routes specifically for Apollo. As you can see in the example below, the routes are both using a 'jwt' auth strategy, but the getRoute mode is set to 'try'. You can also disable the auth altogether by setting it to false. Either way, the playground should then render.

```
await server.register({
  plugin: hapiPlugin,
  options: {
    apolloServer,
    path: '/graphql',
    getRoute: {
      options: {
        auth: {
          strategy: 'jwt',
          mode: 'try'
        }
      }
    },
    postRoute: {
      options: {
        auth: {
          strategy: 'jwt',
        },
        payload: {
          maxBytes: 100 * 1024 * 1024
        }
      }
    },
  } as HapiApolloPluginOptions<any>
});
```

**Comment by bharat-vaggu** [comment]
if I set getRoute mode to 'try', it's working. Thank you!

**Comment by bharat-vaggu** [comment]
I have configured like below

await server.register({
  plugin: hapiPlugin,
  options: {
    apolloServer,
    path: '/graphql',
    getRoute: {
      options: {
        auth: {
          strategy: 'jwt',
          mode: 'try'
        }
      }
    },
    postRoute: {
      options: {
        auth: {
          strategy: 'jwt',
        },
        payload: {
          maxBytes: 100 * 1024 * 1024
        }
      }
    },
  } as HapiApolloPluginOptions<any>
});

But when I call graphql apis with GET method without authorization token, it is not giving authotization error instead it is allowing application. How can we handle this? 

Note - It was working with Apollo Server 3. I know, All graphql call should be with POST method, but safer side it should throw an error with GET method when token is not passed or expired

**Comment by arimus** [comment]
@bharat-vaggu Closing this for now. Re-open or open a new if you still have issues you need assistance with!
