### ISSUE TITLE
@as-integrations npm scope

### ISSUE THREAD

**Issue by trevor-scheer** [apollo-server-integrations/apollo-server-integration-hapi#5]
Hey @arimus - let me know your npmjs handle when you get a chance and I'll get you added to the `@as-integrations` org so you can publish under the scope when you're ready. Looking forward to seeing it live!

**Comment by arimus** [comment]
@trevor-scheer I'm arimus on npmjs as well.

**Comment by trevor-scheer** [comment]
Invite sent!
