### ISSUE TITLE
Update Apollo Server docs when published

### ISSUE THREAD

**Issue by trevor-scheer** [apollo-server-integrations/apollo-server-integration-hapi#7]
https://www.apollographql.com/docs/apollo-server/integrations/integration-index

(located here: https://github.com/apollographql/apollo-server/blob/main/docs/source/integrations/integration-index.mdx)

**Comment by arimus** [comment]
Change request which includes the new Hapi integration has been sent.

**Comment by arimus** [comment]
@trevor-scheer did you see the PR go through for the docs last night or do I need to re-submit? I sent it, but not seeing it in the PR list and the docs aren't updated.

**Comment by trevor-scheer** [comment]
@arimus I don't see an open PR against the `apollo-server` repo. It looks like you made the fork but didn't open the actual PR. Just click the button here: https://github.com/apollographql/apollo-server/compare/main...arimus:apollo-server:patch-2

**Comment by arimus** [comment]
It was late ;) Thanks for the merge!
